"""
mbed SDK
Copyright (c) 2011-2013 ARM Limited

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
from optparse import OptionParser
from workspace_tools.toolchains import TOOLCHAINS
from workspace_tools.targets import TARGET_NAMES


def get_default_options_parser():
    parser = OptionParser()

    targetnames = TARGET_NAMES
    targetnames.sort()
    toolchainlist = list(TOOLCHAINS)
    toolchainlist.sort()

    parser.add_option("-m", "--mcu",
                  help="build for the given MCU (%s)" % ', '.join(targetnames),
                  metavar="MCU")

    parser.add_option("-t", "--tool",
                  help="build using the given TOOLCHAIN (%s)" % ', '.join(toolchainlist),
                  metavar="TOOLCHAIN")

    parser.add_option("-c", "--clean", action="store_true", default=False,
                  help="clean the build directory")

    parser.add_option("-o", "--options", action="append",
                  help='Add a build option ('\
                            '"save-asm": save the asm generated by the compiler, ' \
                            '"debug-info": generate debugging information, ' \
                            '"analyze": run Goanna static code analyzer, '\
                            '"opt-O*": override compiler optimization level, e.g. opt-O2, opt-Otime, etc.)')

    parser.add_option("-j", "--jobs", type="int", dest="jobs", default=1,
                  help="Number of concurrent jobs (default 1). Use 0 for auto based on host machine's number of CPUs")

    parser.add_option("-v", "--verbose",
                  action="store_true", dest="verbose", default=False,
                  help="Verbose diagnostic output")

    parser.add_option("--silent", action="store_true", dest="silent", default=False,
                  help="Silent diagnostic output (no copy, compile notification)")

    parser.add_option("-D", "", action="append", dest="macros",
                  help="Add a macro definition")

    return parser
